CREATE TABLE qc_store.qctask_case_locks (
    case_id NUMBER(10,0) PRIMARY KEY
);
CREATE TABLE qc_store.qctask_task (
    task_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_name VARCHAR2(100 CHAR) NOT NULL,
    task_desc VARCHAR2(200 CHAR),
    task_status VARCHAR2(100 CHAR) DEFAULT 'Not Started' NOT NULL,
    assigned_to VARCHAR2(20 CHAR), assigned_to_name VARCHAR2(100 CHAR),
    task_cmpled_dts TIMESTAMP(6) WITH TIME ZONE,
    status VARCHAR2(20 CHAR) DEFAULT 'Active' NOT NULL,
    created_by VARCHAR2(20 CHAR), created_dts TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by VARCHAR2(20 CHAR), updated_dts TIMESTAMP(6) WITH TIME ZONE,
    task_queue_name VARCHAR2(50 CHAR), case_id NUMBER(10,0) NOT NULL,
    task_comment VARCHAR2(4000), created_by_name VARCHAR2(200 CHAR)
);
CREATE TABLE qc_store.qctask_task_details (
    task_details_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    task_id NUMBER NOT NULL UNIQUE REFERENCES qc_store.qctask_task(task_id),
    task_canonical CLOB NOT NULL CHECK (task_canonical IS JSON),
    status VARCHAR2(20 CHAR) DEFAULT 'Active' NOT NULL,
    created_by VARCHAR2(20 CHAR), created_dts TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by VARCHAR2(20 CHAR), updated_dts TIMESTAMP(6) WITH TIME ZONE
);
CREATE TABLE qc_store.qctask_claim_details (
    case_id NUMBER(10,0) NOT NULL, claim_number VARCHAR2(100 CHAR) NOT NULL,
    claim_data CLOB NOT NULL CHECK (claim_data IS JSON), qc_status VARCHAR2(100 CHAR),
    updated_dts TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (case_id, claim_number)
);
CREATE TABLE qc_store.qctask_claim_messages (
    message_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    task_id NUMBER NOT NULL REFERENCES qc_store.qctask_task(task_id) ON DELETE CASCADE,
    claim_number VARCHAR2(100 CHAR) NOT NULL, sender_racf VARCHAR2(100 CHAR) NOT NULL,
    recipient_racf VARCHAR2(100 CHAR) NOT NULL, assigned_racf VARCHAR2(100 CHAR),
    message_text VARCHAR2(4000) NOT NULL,
    created_dts TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE qc_store.qctask_notifications (
    notification_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    message_id NUMBER REFERENCES qc_store.qctask_claim_messages(message_id) ON DELETE CASCADE,
    task_id NUMBER NOT NULL REFERENCES qc_store.qctask_task(task_id) ON DELETE CASCADE,
    claim_number VARCHAR2(100 CHAR), recipient_racf VARCHAR2(100 CHAR) NOT NULL,
    notification_text VARCHAR2(4000) NOT NULL,
    read_dts TIMESTAMP(6) WITH TIME ZONE,
    created_dts TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UNIQUE (message_id, recipient_racf)
);
CREATE INDEX qc_store.qctask_messages_claim_idx ON qc_store.qctask_claim_messages (task_id, claim_number, created_dts);
CREATE INDEX qc_store.qctask_notifications_user_idx ON qc_store.qctask_notifications (recipient_racf, read_dts, created_dts);
