CREATE SCHEMA IF NOT EXISTS pic_master;

CREATE TABLE IF NOT EXISTS pic_master.task (
    task_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_name VARCHAR(100) NOT NULL,
    task_desc VARCHAR(200),
    task_status VARCHAR(100) NOT NULL DEFAULT 'Not Started',
    assigned_to VARCHAR(20),
    assigned_to_name VARCHAR(100),
    task_cmpled_dts TIMESTAMPTZ,
    status VARCHAR(20) NOT NULL DEFAULT 'Active',
    created_by VARCHAR(20),
    created_dts TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(20),
    updated_dts TIMESTAMPTZ,
    task_queue_name VARCHAR(50),
    case_id NUMERIC(10, 0) NOT NULL,
    task_comment VARCHAR(4000),
    created_by_name VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS pic_master.task_details (
    task_details_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL UNIQUE REFERENCES pic_master.task(task_id),
    task_canonical JSONB NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'Active',
    created_by VARCHAR(20),
    created_dts TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(20),
    updated_dts TIMESTAMPTZ,
    CHECK (jsonb_typeof(task_canonical->'claimsForReviews') = 'array'
           AND task_canonical ? 'claimsForReviews')
);

CREATE TABLE IF NOT EXISTS pic_master.claim_details (
    case_id NUMERIC(10,0) NOT NULL,
    claim_number TEXT NOT NULL,
    claim_data JSONB NOT NULL,
    qc_status TEXT,
    updated_dts TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (case_id, claim_number)
);

ALTER TABLE pic_master.claim_details
    DROP COLUMN IF EXISTS qc_started_dts,
    DROP COLUMN IF EXISTS qc_completed_dts,
    DROP COLUMN IF EXISTS qc_updated_by;

ALTER TABLE pic_master.claim_details DROP CONSTRAINT IF EXISTS claim_details_qc_status_check;
ALTER TABLE pic_master.claim_details ALTER COLUMN qc_status DROP NOT NULL;
ALTER TABLE pic_master.claim_details ALTER COLUMN qc_status DROP DEFAULT;
UPDATE pic_master.claim_details SET qc_status = NULL WHERE qc_status = 'Not Started';
UPDATE pic_master.claim_details SET qc_status = 'Returned for Corrections' WHERE qc_status = 'Action Required';

DROP INDEX IF EXISTS pic_master.one_current_claim_in_details_per_task;
ALTER TABLE pic_master.claim_details
    DROP COLUMN IF EXISTS task_id,
    DROP COLUMN IF EXISTS qc_review_order;

-- Copy legacy review data into canonical JSON before removing duplicate columns.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_schema = 'pic_master' AND table_name = 'claim_details'
                 AND column_name = 'qc_review_details') THEN
        UPDATE pic_master.task_details d SET task_canonical = jsonb_set(
            d.task_canonical, '{claimsForReviews}',
            (SELECT COALESCE(jsonb_agg(
                j.item || jsonb_build_object('qcReviewDetails',
                    COALESCE(c.qc_review_details, '{}'::jsonb)
                    || jsonb_strip_nulls(jsonb_build_object(
                        'outcome', NULLIF(c.qc_outcome, ''),
                        'notes', NULLIF(c.qc_notes, '')))
                    || COALESCE(j.item->'qcReviewDetails', '{}'::jsonb)
                ) ORDER BY j.position), '[]'::jsonb)
             FROM pic_master.task t
             CROSS JOIN LATERAL jsonb_array_elements(d.task_canonical->'claimsForReviews')
                 WITH ORDINALITY AS j(item, position)
             LEFT JOIN pic_master.claim_details c ON c.case_id = t.case_id
                 AND c.claim_number = j.item->>'claimNumber'
             WHERE t.task_id = d.task_id)
        );
    END IF;
END $$;
ALTER TABLE pic_master.claim_details
    DROP COLUMN IF EXISTS eligible_for_qc,
    DROP COLUMN IF EXISTS qc_review_details,
    DROP COLUMN IF EXISTS qc_outcome,
    DROP COLUMN IF EXISTS qc_notes;

CREATE TABLE IF NOT EXISTS pic_master.qc_claim_messages (
    message_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL REFERENCES pic_master.task(task_id) ON DELETE CASCADE,
    claim_number TEXT NOT NULL,
    sender_racf VARCHAR(100) NOT NULL,
    recipient_racf VARCHAR(100) NOT NULL,
    assigned_racf VARCHAR(100),
    message_text VARCHAR(4000) NOT NULL,
    created_dts TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS qc_claim_messages_task_claim_idx
    ON pic_master.qc_claim_messages (task_id, claim_number, created_dts);

CREATE TABLE IF NOT EXISTS pic_master.qc_notifications (
    notification_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    message_id BIGINT REFERENCES pic_master.qc_claim_messages(message_id) ON DELETE CASCADE,
    task_id BIGINT NOT NULL REFERENCES pic_master.task(task_id) ON DELETE CASCADE,
    claim_number TEXT,
    recipient_racf VARCHAR(100) NOT NULL,
    notification_text VARCHAR(4000) NOT NULL,
    read_dts TIMESTAMPTZ,
    created_dts TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (message_id, recipient_racf)
);

ALTER TABLE pic_master.qc_notifications
    ADD COLUMN IF NOT EXISTS task_id BIGINT REFERENCES pic_master.task(task_id) ON DELETE CASCADE,
    ADD COLUMN IF NOT EXISTS claim_number TEXT,
    ADD COLUMN IF NOT EXISTS notification_text VARCHAR(4000);

UPDATE pic_master.qc_notifications n
SET task_id = m.task_id, claim_number = m.claim_number, notification_text = m.message_text
FROM pic_master.qc_claim_messages m
WHERE n.message_id = m.message_id AND n.task_id IS NULL;

ALTER TABLE pic_master.qc_notifications
    ALTER COLUMN message_id DROP NOT NULL,
    ALTER COLUMN task_id SET NOT NULL,
    ALTER COLUMN notification_text SET NOT NULL;

CREATE INDEX IF NOT EXISTS qc_notifications_recipient_unread_idx
    ON pic_master.qc_notifications (recipient_racf, created_dts)
    WHERE read_dts IS NULL;
